### ISSUE TITLE
safe filter with undefined variable, change since 1.0.3

### ISSUE THREAD

**Issue by samuelcolvin** [niwibe/django-jinja#124]
Lets say I have, in view:
```
if whatever:
    self.context['link'] = '<a href="%s">here</a>' % link
```
then in the template
```
view the thing {{ link|safe }}.
```
If `whatever` is true and link is set all is well and the above becomes a link
```
view the thing <a href="/whereever/">here</a>.
```
but if `whatever` is false and link is not set, eg. is undefined it gives
```
view the thing {{ link }}.
```

Eg. the tag doesn't get interpreted to remove the `|safe`.

This is different from the behavior without the safe filter and has occurred between v1.0.3 and v1.3.3. I don't know where as we upgraded straight from 1.0.3 to 1.3.3.

IMHO this is seems like the wrong behavior (I think from memory it's different to standard django?) but if it's intention that's fine.

Temporary fix is
```
view the thing {{ link or ''|safe }}.
```

**Comment by niwibe** [comment]
It is clearly an issue relate to the jinja2 undefined value. https://github.com/niwibe/django-jinja/blob/master/django_jinja/base.py#L276

Since 1.0.3 the undefined values are printed http://jinja.pocoo.org/docs/dev/api/#undefined-types just for debuging purposes, but when settings.DEBUG is turned off the standard behavior is restored.

It seems a lot of confusion with this very useful feature, already introduced in django1.8 :(

**Comment by samuelcolvin** [comment]
ok thanks a lot, so the solutions is to always define the variable in the context?

**Comment by niwibe** [comment]
This kind of behavior helps to the developer see that variables are not found in the context in a very quickly way. As I said previously, this is only happens when DEBUG is True.

The good practice is always have variables that you want to use, or use the `default` filter or something. In any case, the previous behavior (pre 1.0.3) can be restored, setting the "undefined" jinja environment variable to the desired class.

**Comment by niwibe** [comment]
In any case, this afternoon I have plans to release a new version, and maybe I put some special settings for make change this behavior in a easy way.
