### ISSUE TITLE
Default behavior of the `undefined` option.

### ISSUE THREAD

**Issue by Exirel** [niwibe/django-jinja#87]
First, thanks for all the good work to make django-jinja compatible with the future version 1.8 of Django!

I want to draw your attention on something  that isn't that important, but I was very surprised by a change in the behavior between an older version 1.0.x and a the new versions 1.1.x. This change comes from [these few lines](https://github.com/niwibe/django-jinja/blob/51970a68557e16af4c2b1dd3b616e88ac6f43846/django_jinja/backend.py#L52): 

```python
if settings.DEBUG:
    options.setdefault("undefined", jinja2.DebugUndefined)
else:
    options.setdefault("undefined", jinja2.Undefined)
```

The good news is: it works as before in production, with `DEBUG = False`. So no big deal here in the end. However, as it's new to versions 1.1.x, I would like two little things (if it's possible or worth the time):

* A small line or two about the `undefined` option in the documentation,
* And maybe use `settings.TEMPLATE_DEBUG` instead of `settings.DEBUG`?

I was very surprised when I tried locally and saw all these `{{ some_var }}` in my rendered HTML, and I was confused for a minute that `settings.TEMPLATE_DEBUG = False` didn't work as expected.

I could provide a PR, but maybe you want to keep `settings.DEBUG`? And maybe there are other options I don't know about that deserve a modification/a line in the doc/etc.

**Comment by niwibe** [comment]
Hi @Exirel 

Firstly: thank you!

This change is motivated because the django 1.8 default backend introduces that change: https://github.com/django/django/blob/master/django/template/backends/jinja2.py#L32 

You are right about documentation, I completely miss it. Sorry.
About the decision of use TEMPLATE_DEBUG instead of DEBUG, as I said before I have borowed the django behavior, but you are right, semantically TEMPLATE_DEBUG seems a better approach.

As conclusion: change DEBUG to TEMPLATE_DEBUG and add a little note to the documentation. If you can provide a pr, I'll gladly accept it!

Thank you very much.

**Comment by aaugustin** [comment]
For the record, the TEMPLATE_DEBUG setting is documented to [enable stack traces in Django templates](https://docs.djangoproject.com/en/1.7/ref/settings/#template-debug), so I'm not sure about what's semantically better here.

**Comment by aaugustin** [comment]
I've proposed to [remove TEMPLATE_DEBUG](https://code.djangoproject.com/ticket/24344), making this question disappear.

**Comment by niwibe** [comment]
Great! Thank you very much!

**Comment by aaugustin** [comment]
I just pushed this change to Django, including the 1.8 branch.

**Comment by Exirel** [comment]
That's a way to solve an issue. :smile: 
I hope I'll find 5min today to update the doc then.

**Comment by niwibe** [comment]
I have added the missing changelog entry.
